# .github/workflows/ci.yml
name: Run tests on commit

on:
  push:
    branches:
      - develop  # ← このブランチにpushされたときにテストが走る（自由に変えてOK）

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # - name: Install dependencies
    #   run: npm install

    - name: Run tests
      run: npm test
