# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches:
      - master  # PRのマージ先

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Node.js セットアップ
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: 依存関係のインストール
      run: npm install

    - name: テストの実行
      run: npm test
